### ISSUE TITLE
npm install 出错 

### ISSUE THREAD

**Issue by iibrat** [zuoxiaobai/chatgpt-node-vue3#2]
1 package is looking for funding
  run `npm fund` for details

运行 npm fund 之后也不知道是什么意思
PS E:\BaiduSyncdisk\小程序\chatgpt-node-vue3> npm fund
chat-gpt-server@1.0.0
└── https://github.com/sponsors/RubenVerborgh
    └── follow-redirects@1.15.2

**Comment by zuoxiaobai** [comment]
看了下，这个包是 axios 引用的。这个提示不是报错，而是开发者寻求捐赠支持。 可以使用npm install --no-fund 跳过该提示，相同的问题链接：https://www.cnblogs.com/sjj33sda/p/13952527.html
