### ISSUE TITLE
大佬 请问亚马逊的服务器推荐选择哪个地区的？

### ISSUE THREAD

**Issue by nullwu** [zuoxiaobai/chatgpt-node-vue3#3]
大佬 请问亚马逊的服务器推荐哪个地区的？

**Comment by zuoxiaobai** [comment]
我选的是日本-东京，离的近，速度还行。

**Comment by nullwu** [comment]
![image](https://user-images.githubusercontent.com/32824912/233574381-2de487cc-eed1-49ae-8ce9-87bff9b74e05.png)
亚马逊服务器现在不能选择国外地址了吗？只有两个中国的地区选项。这样我该怎么注册国外的服务器呢。
